new TypeIt('#animText')
    .options([lifeLike = true])
    .type('Budi izvrstan u onom što vidiš!')
    .pause(800)
    .delete(6)
    .type('voliš.')
    .pause(800)
    .type('<p id="zaiskri">Zaiskri.</p>')
    .go()